services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  app:
    build: ./delivery_app/restaurant
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres/exampledb
    depends_on:
      - postgres
    restart: always

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"


volumes:
  postgres_data:
  rabbitmq_data:
