version: '3.8'

services:
  postgres-restaurant:
    image: postgres:latest
    volumes:
      - postgres-restaurant-data:/var/lib/postgresql/data-restaurant
    environment:
      POSTGRES_DB: restaurantdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app_network

  postgres-user:
    image: postgres:latest
    volumes:
      - postgres-user-data:/var/lib/postgresql/data-user
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    restart: always
    networks:
      - app_network

  postgres-deliveries:
    image: postgres:latest
    volumes:
      - postgres-deliveries-data:/var/lib/postgresql/data-deliveries
    environment:
      POSTGRES_DB: deliveriesdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    restart: always
    networks:
      - app_network

  postgres-order:
    image: postgres:latest
    volumes:
      - postgres-order-data:/var/lib/postgresql/data-order
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    restart: always
    networks:
      - app_network

  restaurant-app:
    build: ./delivery_app/restaurant
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres-restaurant:5432/restaurantdb
      - JWT_KEY=${JWT_KEY}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    depends_on:
      - postgres-restaurant
      - kong
    restart: always
    networks:
      - app_network

  user-app:
    build: ./delivery_app/user
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres-user:5432/userdb
      - JWT_KEY=${JWT_KEY}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    depends_on:
      - postgres-user
      - kong
    restart: always
    networks:
      - app_network

  deliveries-app:
    build: ./delivery_app/deliveries
    ports:
      - "5002:5002"
    environment:
      DATABASE_URL: postgresql://user:password@postgres-deliveries:5432/deliveriesdb
    depends_on:
      - postgres-deliveries
    restart: always
    networks:
      - app_network

  order-app:
    build: ./delivery_app/order
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres-order:5432/orderdb
      - JWT_KEY=${JWT_KEY}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    depends_on:
      - postgres-order
      - kong
    restart: always
    networks:
      - app_network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - app_network

  kong-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: always
    networks:
      - app_network

  kong:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-db
      KONG_PG_PORT: 5432
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
    depends_on:
      - kong-db
      - kong-migration
    restart: always
    networks:
      - app_network

  konga:
    image: pantsel/konga:latest
    environment:
      NODE_ENV: production
    ports:
      - "1337:1337"
    restart: always
    depends_on:
      - kong
    networks:
      - app_network

  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_PG_PORT: 5432
    depends_on:
      - kong-db
    networks:
      - app_network

  kong-init:
    image: postgres:alpine
    depends_on:
      - kong
    volumes:
      - ./init_kong.sh:/docker-entrypoint-initdb.d/init_kong.sh
    entrypoint: [ "/bin/sh", "/docker-entrypoint-initdb.d/init_kong.sh" ]
    environment:
      PGPASSWORD: kong
      JWT_KEY: ${JWT_KEY}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app_network

volumes:
  postgres-restaurant-data:
  postgres-user-data:
  postgres-deliveries-data:
  postgres-order-data:
  rabbitmq_data:
  kong_data:


networks:
  app_network:
    name: app_network
    driver: bridge
