FROM kong:latest

USER root
RUN apt-get update && apt-get install -y postgresql-client curl
USER kong

CMD ["/bin/sh", "-c", "until pg_isready -h kong-db -p 5432 -U kong; do echo 'Waiting for PostgreSQL to be ready...'; sleep 5; done; kong start;"]
